definitions:
  Project:
    type: object
    properties:
      _id:
        type: string
        description: ObjectId of project
        readOnly: true
      name:
        type: string
        example: Example project
      projectType:
        type: string
        enum: ['single', 'multiple', 'multiple_comparison']
      members:
        type: array
        items:
          type: object
          properties:
            user:
              type: string
              description: Current user's ObjectId
              example: 616e7f034f3bbb2ef4a87ce3
            email:
              type: string
              example: example@infinov.com
            role:
              type: string
              enum: ['owner', 'attendee', 'member']
      task:
        type: object
        properties:
          taskType:
            type: string
            enum: ['ML', 'Vision', 'NLP']
          names:
            type: array
            items:
              type: string
              enum: ['classification', 'regression', 'clustering', 'object detection', 'segmentation', 'feature extraction', 'QnA', 'Translation', 'word feature extraction']
            uniqueItems: true
paths:
  /project:
    get:
      tags:
        - Project
      summary: Retrieve a list of projects
      description: Retrieve a list of projects from db.
      responses:
        200:
          description: A list of projects.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: OK
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Project'
        204:
          description: No project found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 204
                  message:
                    type: string
                    example: No project found.
                  data:
                    type: object
    post:
      tags:
        - Project
      summary: New project
      description: Add a new project to db.
      produces:
        - application/json
      requestBody:
        description: "Note: Property '_id' does not need"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Project'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 201
                  message:
                    type: string
                    example: Created
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Project'
        400:
          description: Project name already in use.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  code:
                    type: number
                    example: 400
                  message:
                    type: string
                    example: Project name already in use.
                  data:
                    type: object
    delete:
      tags:
        - Project
      summary: Delete projects
      description: Delete selected projects.
      produces:
        - application/json
      requestBody:
        description: \'_id\'s of selected projects
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
                  example: ["61721bce16b8e06386ca573c", "61721bf916b8e06386ca573f", "61721bc816b8e06386ca5739"]
      responses:
        200:
          description: deletedCount
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      deletedCount:
                        type: integer
                        example: 3
        404:
          description: No project was deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: No project was deleted.
                  data:
                    type: object
  /project/{id}:
    get:
      tags:
        - Project
      summary: Retrieve a project
      description: Retrieve a project from db.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: path parameter takes the project id
          required: true
          type: string
      responses:
        200:
          description: A project
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: OK
                  data:
                    $ref: '#/definitions/Project'
        404:
          description: A project with the specified ID was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: A project with the specified ID was not found.
                  data:
                    type: object
    put:
      tags:
        - Project
      summary: Modify a project
      description: Modify a project.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: path parameter takes the project id
          required: true
          type: string
      requestBody:
        description: project properties
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Project'
      responses:
        200:
          description: A modified project
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 201
                  message:
                    type: string
                    example: Created
                  data:
                    $ref: '#/definitions/Project'
        404:
          description: No project was modified. (A project with the specified ID was not found)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: No project was modified.
                  data:
                    type: object
    delete:
      tags:
        - Project
      summary: Delete a project
      description: Delete a project.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: path parameter takes the project id
          required: true
          type: string
      responses:
        200:
          description: A deleted project
          content:
            application/json:
              schema:
                $ref: '#/definitions/Project'
        404:
          description: No project was deleted. (A project with the specified ID was not found)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: No project was deleted.
                  data:
                    type: object